### ISSUE TITLE
New routes

### ISSUE THREAD

**Issue by marekberanek** [kratsg/dockerimages#5]
Hello, I would like to ask you to add new routes for listing files / folders and creating / removing folders in EoS.
Best, Marek

**Comment by kratsg** [comment]
Hi @marekberanek , sure. For [eos-krb5-shell2http](https://github.com/kratsg/dockerimages/tree/master/eos-krb5-shell2http) - I'll try to mimic the existing API access and keep the naming consistent enough.

**Comment by kratsg** [comment]
For listing files/folders, this will be done by listing just paths.

`/ls?path=eos/user/g/gstark` gives:
```json
{"content": ["ATLASInduction","AwesomeWorkshopFeb2020","Contacts","Documents","HiFi_MBJ_79800_multibin.tar.gz","MBJ","Music","Pictures","Videos","WINDOWS","public","pyhf","susy","www"], "path": "eos/user/g/gstark", "message": "Ok."}
```

**Comment by kratsg** [comment]
Relevant commits: 
- 5787b79174e7699d0c8418fe9ce79fa5fcaa6b1f
- 6548945d299470369b1a38776c2d0a63473231b5
- d6659585007c05e885833afb8286173ece2493df
- ed660b82e7f76aa8924005a09bce42d6c33fccee
- 59448725b4775a0ce733a377b0299364806cec5e
